### PR TITLE
Monster will spawn 10 seconds after death

### PR DESCRIPTION
**Pull request by nihrom**

### CODE REVIEW

**Comment by nihrom** [comment]
Yes, I checked the working capacity. Forgot to delete before the last commit.

**Comment by Elfocrash** [comment]
The status listener is used to track the status of the attacker. Are you sure it's not breaking this behaviour?

**Comment by nihrom** [comment]
Yes

**Comment by Elfocrash** [comment]
Can go in NPCs https://github.com/Elfocrash/L2dotNET/blob/master/src/L2dotNET/Datapacks/Game/config/npcs.json

**Comment by nihrom** [comment]
In this file, I did not find the respawn time information. But in the database in the table spawnlist is the value respawn_delay. It `s that?

**Comment by Elfocrash** [comment]
Yeap, perfect. Thanks!

**Pull request merged**
